Poc 115
AMPATH/etl-rest-server pull request #1232
Opened 2023-03-23 09:32 UTC by hiqedme

Family enhancements

2023-03-23 12:16 UTC, drizzentic commented on app/family-history/family-history.service.js
> +        sql =
Might want to use shorthand appending i.e `sql+=`

2023-03-23 12:17 UTC, drizzentic commented on app/family-history/family-history.service.js
> +      //  ' tx.*, t8.status, extract(year from (from_days(datediff(now(),tx.birthdate)))) as age, tx.gender as index_gender, 1 as hideContactColumns ' +
Do we need this code here?

2023-03-23 12:18 UTC, drizzentic commented on app/family-history/family-history.service.js
> +      columns + // ' tx.*,t8.status,extract(year from (from_days(datediff(now(),tx.birthdate)))) as age, tx.gender as index_gender, 1 as hideContactColumns ' +
Consider removing any commented code.

2023-04-03 09:13 UTC, corneliouzbett requested changes

2023-04-03 09:13 UTC, corneliouzbett commented on package-lock.json
I don't what's happening here but these changes are unnecessary since you haven't changed a thing in the `package.json`

2023-04-03 16:21 UTC, corneliouzbett approved these changes

2023-04-03 16:22 UTC, merged