Poc 367
AMPATH/etl-rest-server pull request #1291
Opened 2023-07-05 12:04 UTC by drizzentic

2023-07-10 06:49 UTC, corneliouzbett requested changes

2023-07-10 06:49 UTC, corneliouzbett commented on docker-compose.yml
> +    image: ampathke/etl-services:POC-399
Does this mean, we will be changing this in every PR??

2023-07-10 06:49 UTC, corneliouzbett commented on programs/scope-builder.service.js
> +  console.log('has initial', initialEncounters, dateEnrolled);
Please clean up the console logs
```suggestion
  let latestEnc = initialEncounters[initialEncounters.length - 1];
```

2023-07-10 06:49 UTC, corneliouzbett commented on programs/scope-builder.service.js
> +    console.log('wapo');
Ditto
```suggestion
```

2023-07-10 06:51 UTC, drizzentic commented on docker-compose.yml
> +    image: ampathke/etl-services:POC-399
Ideally, it's supposed to be the docker image name for the deployed commit

2023-07-12 05:45 UTC, corneliouzbett approved these changes

2023-07-12 06:29 UTC, corneliouzbett approved these changes

2023-07-12 07:54 UTC, merged